"""
Prompts for the Planning Agent.

The planning agent consumes architecture knowledge and ticket information
to produce a ticket-specific implementation plan.
"""

import json
from typing import Any


def system_prompt() -> str:
    """System prompt for the planning agent."""
    return (
        "You are a senior software architect. "
        "You create detailed implementation plans based on project architecture "
        "and ticket requirements. "
        "Return only valid JSON. Do not use markdown or code fences."
    )


def user_prompt(
    workflow: dict[str, Any],
    architecture_knowledge: dict[str, Any] | None = None,
) -> str:
    """
    Build the user prompt for the planning agent.

    Args:
        workflow: The workflow event with ticket information.
        architecture_knowledge: Optional architecture knowledge from S3
                                (generated by architecture agent).
    """
    architecture_section = ""
    if architecture_knowledge:
        architecture_section = f"""
--------------------------------------------------
Project Architecture (Knowledge Base)
--------------------------------------------------

{json.dumps(architecture_knowledge, indent=2)}

Use this architecture knowledge to inform your implementation plan.
Respect existing patterns, conventions, and folder organization.
"""

    return f"""Generate a detailed implementation plan for this ticket.

Return ONLY a valid JSON object.
Use EXACTLY the schema below.
Do not add extra fields. Do not rename fields.
Do not wrap the response in markdown.
Populate EVERY field with meaningful content.

For filesToGenerate, include all source files that should be created or modified
with realistic filenames that respect the project's folder organization.

--------------------------------------------------
Ticket Information
--------------------------------------------------

Ticket ID: {workflow.get("ticketId", "")}
Summary: {workflow.get("summary", "")}
Description: {workflow.get("description", "")}
Priority: {workflow.get("priority", "")}
Issue Type: {workflow.get("issueType", "")}
Project: {workflow.get("project", "")}
{architecture_section}
--------------------------------------------------
Required JSON Schema
--------------------------------------------------

{{
  "summary": "",
  "requirements": [],
  "acceptanceCriteria": [],
  "implementationPlan": [],
  "testCases": [],
  "affectedModules": [],
  "technologies": [],
  "filesToGenerate": []
}}"""
