"""
Prompts for the Planning Agent.

The planning agent consumes architecture knowledge and ticket information
to produce a ticket-specific Engineering Contract (implementation plan).

The Engineering Contract includes:
- Traditional planning fields (summary, requirements, etc.)
- Change classification (changeType, intent, riskLevel, estimatedScope)
- Module analysis (candidateModules, expectedFileTypes, avoidFileTypes)
- Safety constraints (expectedChanges, mustNotChange, validationChecklist)
"""

import json
from typing import Any


def system_prompt() -> str:
    """System prompt for the planning agent."""
    return (
        "You are a senior software architect who produces Engineering Contracts "
        "for development teams.\n\n"
        "An Engineering Contract defines:\n"
        "- WHAT should change\n"
        "- WHAT should NOT change\n"
        "- HOW to validate the result\n\n"
        "You classify every ticket into one of these change types:\n"
        "- BUG_FIX: Fixing broken behavior\n"
        "- NEW_FEATURE: Adding entirely new functionality\n"
        "- ENHANCEMENT: Improving existing functionality\n"
        "- REFACTOR: Restructuring code without changing behavior\n"
        "- CONFIGURATION: Changing config, environment, or build settings\n"
        "- DOCUMENTATION: Updating docs, comments, or README\n\n"
        "RULES:\n"
        "1. Return only valid JSON. No markdown. No code fences.\n"
        "2. Do NOT guess file paths. Use logical module names instead.\n"
        "3. Be precise about what should and should NOT change.\n"
        "4. For UI text changes, avoid suggesting TypeScript/logic file changes.\n"
        "5. For backend changes, avoid suggesting template/style file changes.\n"
        "6. Always produce a machine-readable validation checklist.\n"
        "7. Keep the intent concise — one sentence.\n"
    )


def user_prompt(
    workflow: dict[str, Any],
    architecture_knowledge: dict[str, Any] | None = None,
) -> str:
    """
    Build the user prompt for the planning agent.

    Args:
        workflow: The workflow event with ticket information.
        architecture_knowledge: Optional architecture knowledge from S3
                                (generated by architecture agent).
    """
    architecture_section = ""
    if architecture_knowledge:
        architecture_section = f"""
--------------------------------------------------
Project Architecture (Knowledge Base)
--------------------------------------------------

{json.dumps(architecture_knowledge, indent=2)}

Use this architecture knowledge to inform your Engineering Contract.
Respect existing patterns, conventions, and folder organization.
"""

    return f"""Generate an Engineering Contract for this ticket.

Return ONLY a valid JSON object.
Use EXACTLY the schema below.
Do not add extra fields. Do not rename fields.
Do not wrap the response in markdown.
Populate EVERY field with meaningful content.

--------------------------------------------------
Ticket Information
--------------------------------------------------

Ticket ID: {workflow.get("ticketId", "")}
Summary: {workflow.get("summary", "")}
Description: {workflow.get("description", "")}
Priority: {workflow.get("priority", "")}
Issue Type: {workflow.get("issueType", "")}
Project: {workflow.get("project", "")}
{architecture_section}
--------------------------------------------------
Required JSON Schema
--------------------------------------------------

{{
  "summary": "",
  "requirements": [],
  "acceptanceCriteria": [],
  "implementationPlan": [],
  "testCases": [],
  "affectedModules": [],
  "technologies": [],
  "filesToGenerate": [],

  "changeType": "BUG_FIX | NEW_FEATURE | ENHANCEMENT | REFACTOR | CONFIGURATION | DOCUMENTATION",
  "intent": "One concise sentence describing the engineering intent",
  "candidateModules": ["Logical module names that may need changes, e.g. Login, Dashboard, Orders"],
  "expectedFileTypes": ["File extensions expected to change, e.g. html, css, ts, py"],
  "avoidFileTypes": ["File extensions that should NOT be modified for this ticket"],
  "expectedChanges": ["Specific changes expected, e.g. Update welcome text from X to Y"],
  "mustNotChange": ["Things that must NOT be modified, e.g. Business logic, Authentication"],
  "validationChecklist": ["Machine-readable validation points to verify the change"],
  "riskLevel": "LOW | MEDIUM | HIGH",
  "estimatedScope": "SMALL | MEDIUM | LARGE"
}}

--------------------------------------------------
Classification Guide
--------------------------------------------------

changeType:
- BUG_FIX: Something is broken and needs fixing
- NEW_FEATURE: Brand new functionality that does not exist yet
- ENHANCEMENT: Improving or modifying existing functionality
- REFACTOR: Restructuring without behavior change
- CONFIGURATION: Config/env/build changes
- DOCUMENTATION: Docs, comments, README updates

riskLevel:
- LOW: Isolated change, no side effects expected
- MEDIUM: Touches shared code or multiple modules
- HIGH: Critical path, authentication, data integrity

estimatedScope:
- SMALL: 1-2 files, minor change
- MEDIUM: 3-5 files, moderate changes
- LARGE: 6+ files, significant changes

--------------------------------------------------
Examples
--------------------------------------------------

Example 1: UI text change ticket
- changeType: "ENHANCEMENT"
- intent: "Modify the login page welcome text without changing application logic."
- candidateModules: ["Login"]
- expectedFileTypes: ["html"]
- avoidFileTypes: ["ts", "scss", "spec"]
- expectedChanges: ["Update displayed welcome text"]
- mustNotChange: ["Business logic", "Authentication flow", "Services", "Routing"]
- validationChecklist: ["New text is displayed", "Old text is no longer visible", "Component renders", "No logic changes"]
- riskLevel: "LOW"
- estimatedScope: "SMALL"

Example 2: Add new API endpoint
- changeType: "NEW_FEATURE"
- intent: "Create a new REST endpoint for employee search with pagination."
- candidateModules: ["Employee", "API"]
- expectedFileTypes: ["ts", "spec"]
- avoidFileTypes: ["html", "css", "scss"]
- expectedChanges: ["New controller method", "New service method", "New route registration"]
- mustNotChange: ["Existing endpoints", "Authentication middleware", "Database schema"]
- validationChecklist: ["Endpoint returns 200", "Pagination works", "Auth required", "Unit tests pass"]
- riskLevel: "MEDIUM"
- estimatedScope: "MEDIUM"

--------------------------------------------------

Now generate the Engineering Contract for the ticket above.
Return ONLY the JSON object."""
