"""
Planning Agent Lambda Handler.

The Planning Agent acts as the Technical Lead:
1. Reads architecture knowledge from S3.
2. Generates an Engineering Contract (change classification, intent, constraints).
3. Searches the target GitHub repository for relevant files.
4. Downloads top candidate files.
5. Asks the LLM to produce an implementationContract with exact file paths,
   operations (MODIFY/CREATE), protected files, and validation checklist.

The Development Agent consumes the implementationContract as an Implementer.

Input: Workflow event from Step Functions containing ticket information.
Output: Workflow event enriched with 'planning' and status 'PLANNED'.
"""

import re
from decimal import Decimal
from hashlib import sha256
from typing import Any

from shared.bedrock_client import BedrockClient
from shared.config import PlanningConfig
from shared.dynamodb_helper import WorkflowTable
from shared.github_client import GitHubClient
from shared.logger import get_logger
from shared.prompts import planning as prompts
from shared.s3_helper import S3Helper

logger = get_logger(__name__, agent="planning")

# Maximum candidate files to download from the repository
MAX_CANDIDATE_FILES = 10

# Maximum files whose content is sent to the LLM for contract generation.
# Bumped from 5 to 8 to make room for integration-hub files (below) without
# starving out the keyword-matched candidates that are usually most relevant.
MAX_FILES_FOR_CONTRACT = 8

# File name fragments that almost always act as "integration hubs" — routing
# config, root/shell/dashboard containers, and app modules. When a ticket adds
# or changes UI (new component/tile/page) or touches auth/navigation, these
# files MUST be considered as candidates even if they don't match ticket
# keywords, otherwise the LLM never sees the parent that needs to render/route
# the new piece and it ends up created but never wired in (see SCRUM-16).
INTEGRATION_HUB_HINTS = [
    "app.routes",
    "app-routing",
    "routing.module",
    "app.module",
    "app.component",
    "dashboard.component",
    "home.component",
    "main-layout",
    "shell.component",
    "layout.component",
    "nav",
]

# Maximum number of hub files force-included regardless of keyword score
MAX_HUB_CANDIDATES = 5

# Valid values for enum-like fields (used for validation/defaults)
VALID_CHANGE_TYPES = {
    "BUG_FIX",
    "NEW_FEATURE",
    "ENHANCEMENT",
    "REFACTOR",
    "CONFIGURATION",
    "DOCUMENTATION",
}
VALID_RISK_LEVELS = {"LOW", "MEDIUM", "HIGH"}
VALID_SCOPES = {"SMALL", "MEDIUM", "LARGE"}


# ---------------------------------------------------------------------------
# Architecture knowledge
# ---------------------------------------------------------------------------


def _load_architecture_knowledge(s3: S3Helper) -> dict[str, Any] | None:
    """
    Load the architecture knowledge base from S3.

    This is the JSON generated by the Architecture Agent.
    Returns None if not available (first run, or architecture agent hasn't run yet).
    """
    try:
        if s3.object_exists("architecture/knowledge.json"):
            knowledge = s3.download_json("architecture/knowledge.json")
            logger.info("Architecture knowledge loaded from S3")
            return knowledge
    except Exception as ex:
        logger.warning("Could not load architecture knowledge", error=str(ex))

    return None


# ---------------------------------------------------------------------------
# Keyword extraction
# ---------------------------------------------------------------------------


def _extract_keywords(event: dict[str, Any]) -> list[str]:
    """
    Extract search keywords from the ticket.

    Sources:
        - Ticket summary
        - Ticket description
        - Architecture knowledge module names (if available in planning)

    Returns:
        Deduplicated list of keywords (lowercased, min 3 chars).
    """
    keywords: set[str] = set()

    stop_words = {
        "the",
        "and",
        "for",
        "from",
        "with",
        "this",
        "that",
        "have",
        "has",
        "are",
        "was",
        "were",
        "been",
        "being",
        "will",
        "would",
        "could",
        "should",
        "can",
        "may",
        "might",
        "shall",
        "not",
        "but",
        "its",
        "into",
        "over",
        "under",
        "between",
        "change",
        "update",
        "add",
        "remove",
        "fix",
        "implement",
        "create",
        "delete",
        "modify",
        "please",
        "need",
        "want",
        "text",
        "page",
    }

    # From ticket summary
    summary = event.get("summary", "")
    words = re.findall(r"[a-zA-Z]+", summary)
    for word in words:
        w = word.lower()
        if len(w) >= 3 and w not in stop_words:
            keywords.add(w)

    # From ticket description
    description = event.get("description", "")
    desc_words = re.findall(r"[a-zA-Z]+", description)
    for word in desc_words:
        w = word.lower()
        if len(w) >= 3 and w not in stop_words:
            keywords.add(w)

    return list(keywords)


# ---------------------------------------------------------------------------
# Repository search
# ---------------------------------------------------------------------------


def _find_integration_hub_candidates(
    github: GitHubClient,
    change_type: str,
) -> list[str]:
    """
    Find "integration hub" files that should always be considered as planning
    candidates for UI/navigation-affecting tickets, regardless of keyword match.

    Rationale: a new component/tile/page is only "done" if some existing parent
    (routing config, app module, dashboard/home container) actually references
    it. Pure keyword search over file paths can easily miss that parent if its
    name doesn't share words with the ticket text (e.g. ticket says "Recipe
    tile", parent file is "dashboard.component.ts"). Missing that parent is
    exactly what caused SCRUM-16 (tiles created but never rendered) and
    contributed to SCRUM-9 (login worked but never navigated home).

    Only applies for NEW_FEATURE/ENHANCEMENT changes — bug fixes / config /
    docs changes don't need this widening.

    Args:
        github: Initialized GitHubClient.
        change_type: The Engineering Contract's changeType.

    Returns:
        List of matching file paths (capped at MAX_HUB_CANDIDATES).
    """
    if change_type not in ("NEW_FEATURE", "ENHANCEMENT"):
        return []

    try:
        all_files = github.get_all_files()
    except Exception as ex:
        logger.warning("Could not list repo files for hub search", error=str(ex))
        return []

    hub_paths: list[str] = []
    for item in all_files:
        path = item.get("path", "")
        path_lower = path.lower()
        if any(hint in path_lower for hint in INTEGRATION_HUB_HINTS):
            hub_paths.append(path)
        if len(hub_paths) >= MAX_HUB_CANDIDATES:
            break

    if hub_paths:
        logger.info("Integration hub candidates found", hub_paths=hub_paths)

    return hub_paths


def _search_repository(
    github: GitHubClient,
    keywords: list[str],
    candidate_modules: list[str],
    expected_file_types: list[str],
    change_type: str = "",
) -> list[str]:
    """
    Search the repository for relevant files using keywords and module names.

    Combines keyword search results with module-based search, and always
    force-includes known "integration hub" files (routing, app module,
    dashboard/home containers) for UI-affecting tickets so the Planning Agent
    can see — and plan to modify — the parent that must wire in new components.

    Args:
        github: Initialized GitHubClient.
        keywords: Keywords extracted from the ticket.
        candidate_modules: Logical module names from the Engineering Contract.
        expected_file_types: Expected file extensions from the Engineering Contract.
        change_type: The Engineering Contract's changeType, used to decide
            whether integration-hub widening applies.

    Returns:
        Deduplicated list of candidate file paths (max MAX_CANDIDATE_FILES).
    """
    # Combine keywords with candidate module names for broader search
    all_keywords = list(keywords)
    for module in candidate_modules:
        module_parts = re.findall(r"[a-zA-Z]+", module)
        for part in module_parts:
            if len(part) >= 3 and part.lower() not in all_keywords:
                all_keywords.append(part.lower())

    # Search by keywords
    search_results = github.search_files_by_keywords(
        keywords=all_keywords,
        max_results=MAX_CANDIDATE_FILES,
    )

    candidate_paths = [r["path"] for r in search_results]

    # If we have expected file types, also search by extension to widen the net
    if expected_file_types and len(candidate_paths) < MAX_CANDIDATE_FILES:
        extensions = [f".{ext.lstrip('.')}" for ext in expected_file_types]
        for module in candidate_modules:
            module_lower = module.lower()
            ext_results = github.find_files(extensions=extensions, contains=module_lower)
            for path in ext_results:
                if path not in candidate_paths:
                    candidate_paths.append(path)
                if len(candidate_paths) >= MAX_CANDIDATE_FILES:
                    break
            if len(candidate_paths) >= MAX_CANDIDATE_FILES:
                break

    # Always force-include integration hub files for UI/navigation tickets.
    # These are PREPENDED (not appended) so that _download_candidates, which
    # only downloads the first MAX_FILES_FOR_CONTRACT paths, is guaranteed to
    # fetch them and show their content to the LLM — a hub file that's present
    # in the candidate list but never downloaded is just as useless as one
    # that was never found at all.
    hub_paths = _find_integration_hub_candidates(github, change_type)
    ordered_paths = [p for p in hub_paths if p not in candidate_paths]
    ordered_paths.extend(candidate_paths)

    logger.info(
        "Repository search complete",
        keyword_count=len(all_keywords),
        candidates_found=len(ordered_paths),
        hub_candidates=len(hub_paths),
        candidates=ordered_paths,
    )

    return ordered_paths


# ---------------------------------------------------------------------------
# Download candidate files
# ---------------------------------------------------------------------------


def _download_candidates(
    github: GitHubClient,
    candidate_paths: list[str],
) -> tuple[dict[str, str], dict[str, str]]:
    """
    Download content of the top candidate files and compute SHA256 hashes.

    Only downloads up to MAX_FILES_FOR_CONTRACT files to keep
    the LLM context manageable.

    Args:
        github: Initialized GitHubClient.
        candidate_paths: List of file paths to download.

    Returns:
        Tuple of (path -> file content, path -> SHA256 hex digest).
    """
    paths_to_download = candidate_paths[:MAX_FILES_FOR_CONTRACT]
    logger.info(
        "Downloading candidate files for contract",
        file_count=len(paths_to_download),
        files=paths_to_download,
    )
    contents = github.get_multiple_files(paths_to_download)

    # Compute SHA256 for each downloaded file
    hashes: dict[str, str] = {}
    for path, content in contents.items():
        hashes[path] = sha256(content.encode("utf-8")).hexdigest()

    logger.info("SHA256 hashes computed", file_count=len(hashes))

    return contents, hashes


# ---------------------------------------------------------------------------
# Implementation contract generation
# ---------------------------------------------------------------------------


def _generate_implementation_contract(
    bedrock: BedrockClient,
    event: dict[str, Any],
    planning: dict[str, Any],
    candidate_paths: list[str],
    file_contents: dict[str, str],
    file_hashes: dict[str, str],
    architecture_knowledge: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    Ask the LLM to produce an implementationContract with exact file decisions.

    The LLM receives the ticket, Engineering Contract, candidate files and their
    content, and returns precise MODIFY/CREATE decisions per file.

    After generation, enriches each file entry with:
    - confidence: LLM's confidence score (or default 0.9)
    - sha256: hash of the file at the time of planning (for MODIFY operations)

    Args:
        bedrock: Initialized BedrockClient.
        event: Workflow event with ticket info.
        planning: Engineering Contract (first LLM pass).
        candidate_paths: All candidate file paths found in the repo.
        file_contents: Downloaded file contents (path -> content).
        file_hashes: SHA256 hashes of downloaded files (path -> hex digest).
        architecture_knowledge: Architecture knowledge from S3.

    Returns:
        implementationContract dict, or a fallback if LLM call fails.
    """
    try:
        contract = bedrock.converse_json(
            system_prompt=prompts.implementation_contract_system_prompt(),
            user_prompt=prompts.implementation_contract_user_prompt(
                workflow=event,
                planning=planning,
                candidate_paths=candidate_paths,
                file_contents=file_contents,
                architecture_knowledge=architecture_knowledge,
            ),
            max_tokens=4096,
            temperature=0.1,
        )

        # Validate structure
        contract = _validate_implementation_contract(contract)

        # Enrich each file with confidence and SHA256
        contract = _enrich_contract_files(contract, file_hashes)

        logger.info(
            "Implementation contract generated",
            file_count=len(contract.get("files", [])),
            protected_count=len(contract.get("protectedFiles", [])),
        )

        return contract

    except Exception as ex:
        logger.warning(
            "Implementation contract generation failed, using fallback",
            error=str(ex),
        )
        return _build_fallback_contract(planning, candidate_paths, file_hashes)


def _validate_implementation_contract(contract: dict[str, Any]) -> dict[str, Any]:
    """
    Validate and normalize the implementationContract from the LLM.

    Ensures required fields exist with correct types.
    """
    # Ensure top-level fields
    if not isinstance(contract.get("files"), list):
        contract["files"] = []

    if not isinstance(contract.get("protectedFiles"), list):
        contract["protectedFiles"] = []

    if not isinstance(contract.get("allowedOperations"), list):
        contract["allowedOperations"] = ["MODIFY", "CREATE"]

    if not isinstance(contract.get("validationChecklist"), list):
        contract["validationChecklist"] = []

    # Validate each file entry
    validated_files: list[dict[str, Any]] = []
    for entry in contract["files"]:
        if not isinstance(entry, dict):
            continue
        if not entry.get("path"):
            continue
        if entry.get("operation") not in ("MODIFY", "CREATE"):
            entry["operation"] = "MODIFY"
        if not isinstance(entry.get("reason"), str):
            entry["reason"] = ""
        if not isinstance(entry.get("expectedChanges"), list):
            entry["expectedChanges"] = []
        if not isinstance(entry.get("integratesWith"), list):
            entry["integratesWith"] = []
        validated_files.append(entry)

    contract["files"] = validated_files

    # Generic orphan-CREATE detection (applies to every ticket, not just this one):
    # if the LLM created a new file but never listed a parent file that
    # integrates with it, and no MODIFY entry in the same contract exists,
    # flag it loudly in the validation checklist so the Development Agent's
    # self-review and build validation stay alert to it, and so it's visible
    # in logs/dashboard for human review even if the LLM never catches it.
    modify_paths = {f["path"] for f in validated_files if f.get("operation") == "MODIFY"}
    for entry in validated_files:
        if entry.get("operation") != "CREATE":
            continue
        integrates_with = entry.get("integratesWith") or []
        has_wiring_modify = any(p in modify_paths for p in integrates_with)
        if not integrates_with or not has_wiring_modify:
            logger.warning(
                "CREATE entry has no confirmed parent integration — "
                "component may end up created but never rendered/registered",
                path=entry["path"],
                integrates_with=integrates_with,
            )
            contract["validationChecklist"].append(
                f"VERIFY INTEGRATION: '{entry['path']}' is newly created — confirm it is "
                f"actually imported/declared/rendered by a parent file before merging."
            )

    return contract


def _enrich_contract_files(
    contract: dict[str, Any],
    file_hashes: dict[str, str],
) -> dict[str, Any]:
    """
    Enrich each file in the contract with confidence and SHA256 hash.

    - confidence: Uses the LLM-provided value if present, otherwise defaults to 0.9.
    - sha256: The hash of the file content at the time of planning.
      Only set for MODIFY operations (file must already exist).
      Allows the Development Agent to detect if the file changed
      between planning and implementation.

    Args:
        contract: Validated implementation contract.
        file_hashes: SHA256 hashes from downloaded files (path -> hex digest).

    Returns:
        Enriched contract.
    """
    for file_entry in contract.get("files", []):
        # Confidence: keep LLM value if valid, otherwise default
        if not isinstance(file_entry.get("confidence"), (int, float)):
            file_entry["confidence"] = 0.9

        # SHA256: attach hash for MODIFY operations so the Development Agent
        # can verify the file hasn't changed before modifying it
        path = file_entry.get("path", "")
        if file_entry.get("operation") == "MODIFY" and path in file_hashes:
            file_entry["sha256"] = file_hashes[path]
        elif file_entry.get("operation") == "CREATE":
            file_entry["sha256"] = None
        else:
            # MODIFY but file wasn't downloaded (edge case)
            file_entry["sha256"] = None

    return contract


def _build_fallback_contract(
    planning: dict[str, Any],
    candidate_paths: list[str],
    file_hashes: dict[str, str] | None = None,
) -> dict[str, Any]:
    """
    Build a fallback implementationContract from the Engineering Contract.

    Used when the LLM contract generation call fails.
    """
    file_hashes = file_hashes or {}
    files: list[dict[str, Any]] = []

    # Use filesToGenerate from the engineering contract as a base
    for path in planning.get("filesToGenerate", []):
        operation = "MODIFY" if path in candidate_paths else "CREATE"
        files.append(
            {
                "path": path,
                "operation": operation,
                "reason": "From engineering contract filesToGenerate",
                "expectedChanges": planning.get("expectedChanges", []),
                "confidence": 0.7,
                "sha256": file_hashes.get(path) if operation == "MODIFY" else None,
            }
        )

    return {
        "files": files,
        "protectedFiles": planning.get("mustNotChange", []),
        "allowedOperations": ["MODIFY", "CREATE"],
        "validationChecklist": planning.get("validationChecklist", []),
    }


# ---------------------------------------------------------------------------
# Engineering Contract validation
# ---------------------------------------------------------------------------


def _validate_engineering_contract(planning: dict[str, Any]) -> dict[str, Any]:
    """
    Validate and normalize Engineering Contract fields.

    Ensures all new fields exist with correct types and valid enum values.
    Falls back to sensible defaults if the LLM returned unexpected values.
    """
    # Validate changeType
    change_type = planning.get("changeType", "")
    if change_type not in VALID_CHANGE_TYPES:
        planning["changeType"] = "ENHANCEMENT"
        logger.warning(
            "Invalid changeType from LLM, defaulting to ENHANCEMENT",
            raw_value=change_type,
        )

    # Validate intent (must be a non-empty string)
    if not isinstance(planning.get("intent"), str) or not planning["intent"].strip():
        planning["intent"] = planning.get("summary", "")

    # Validate list fields — ensure they are lists
    list_fields = [
        "candidateModules",
        "expectedFileTypes",
        "avoidFileTypes",
        "expectedChanges",
        "mustNotChange",
        "validationChecklist",
    ]
    for field in list_fields:
        if not isinstance(planning.get(field), list):
            planning[field] = []

    # Validate riskLevel
    risk_level = planning.get("riskLevel", "")
    if risk_level not in VALID_RISK_LEVELS:
        planning["riskLevel"] = "MEDIUM"
        logger.warning(
            "Invalid riskLevel from LLM, defaulting to MEDIUM",
            raw_value=risk_level,
        )

    # Validate estimatedScope
    scope = planning.get("estimatedScope", "")
    if scope not in VALID_SCOPES:
        planning["estimatedScope"] = "MEDIUM"
        logger.warning(
            "Invalid estimatedScope from LLM, defaulting to MEDIUM",
            raw_value=scope,
        )

    return planning


# ---------------------------------------------------------------------------
# Fallback plan
# ---------------------------------------------------------------------------


def _build_fallback_plan(event: dict[str, Any], error: str) -> dict[str, Any]:
    """
    Build a fallback planning dict when Bedrock call fails.

    Includes both legacy fields and new Engineering Contract fields
    to maintain backward compatibility.
    """
    return {
        # Legacy fields
        "summary": event.get("summary", ""),
        "requirements": [],
        "acceptanceCriteria": [],
        "implementationPlan": [],
        "testCases": [],
        "affectedModules": [],
        "technologies": [],
        "filesToGenerate": [],
        # Engineering Contract fields
        "changeType": "ENHANCEMENT",
        "intent": event.get("summary", ""),
        "candidateModules": [],
        "expectedFileTypes": [],
        "avoidFileTypes": [],
        "expectedChanges": [],
        "mustNotChange": [],
        "validationChecklist": [],
        "riskLevel": "MEDIUM",
        "estimatedScope": "MEDIUM",
        # Implementation Contract (empty fallback)
        "implementationContract": {
            "files": [],
            "protectedFiles": [],
            "allowedOperations": ["MODIFY", "CREATE"],
            "validationChecklist": [],
        },
        # Metadata
        "confidence": Decimal("0.50"),
        "estimatedFiles": 0,
        "error": error,
    }


# ---------------------------------------------------------------------------
# Adaptive Replanning
# ---------------------------------------------------------------------------


def _adaptive_replan(
    bedrock: BedrockClient,
    github: GitHubClient,
    event: dict[str, Any],
    changed_files: list[str],
    original_contract: dict[str, Any],
    architecture_knowledge: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    Perform adaptive replanning for files that changed since the original plan.

    Instead of re-planning the entire ticket, this:
    1. Downloads fresh content of the changed files FROM THE FEATURE BRANCH.
    2. Computes new SHA256 hashes from the feature branch.
    3. Asks the LLM to produce an updated implementationContract
       that accounts for the new file state.
    4. Preserves all unchanged decisions from the original contract.

    Args:
        bedrock: Initialized BedrockClient.
        github: Initialized GitHubClient.
        event: Workflow event with ticket info.
        changed_files: List of file paths that had SHA mismatches.
        original_contract: The original implementationContract that failed.
        architecture_knowledge: Architecture knowledge from S3.

    Returns:
        Updated planning dict with new implementationContract.
    """
    replan_attempt = event.get("replanAttempt", 1)

    # Use the feature branch that Development Agent was working on
    target_branch = event.get("replanBranch", "main")

    logger.info(
        "Adaptive replan: downloading fresh file content from feature branch",
        changed_files=changed_files,
        replan_attempt=replan_attempt,
        target_branch=target_branch,
    )

    # Download fresh content of changed files FROM THE FEATURE BRANCH
    fresh_contents: dict[str, str] = {}
    fresh_hashes: dict[str, str] = {}

    for path in changed_files:
        try:
            content = github.get_file_content(path, branch=target_branch)
            fresh_contents[path] = content
            fresh_hashes[path] = sha256(content.encode("utf-8")).hexdigest()
        except Exception:
            # Fallback to main if file doesn't exist on feature branch
            try:
                content = github.get_file_content(path)
                fresh_contents[path] = content
                fresh_hashes[path] = sha256(content.encode("utf-8")).hexdigest()
            except Exception as ex:
                logger.warning("Could not download changed file", path=path, error=str(ex))

    # Get original files from the contract that did NOT change
    original_files = original_contract.get("files", [])
    unchanged_files = [f for f in original_files if f["path"] not in changed_files]
    changed_file_entries = [f for f in original_files if f["path"] in changed_files]

    logger.info(
        "Adaptive replan: files partitioned",
        unchanged_count=len(unchanged_files),
        changed_count=len(changed_file_entries),
    )

    # Ask LLM to produce updated contract for changed files only
    try:
        updated_entries = bedrock.converse_json(
            system_prompt=_replan_system_prompt(),
            user_prompt=_replan_user_prompt(
                event=event,
                changed_file_entries=changed_file_entries,
                fresh_contents=fresh_contents,
                original_contract=original_contract,
            ),
            max_tokens=4096,
            temperature=0.1,
        )

        # Validate the response
        updated_files = updated_entries.get("files", [])
        if not isinstance(updated_files, list):
            updated_files = changed_file_entries  # fallback to original entries

        # Update SHA256 hashes for changed files
        for entry in updated_files:
            path = entry.get("path", "")
            if path in fresh_hashes:
                entry["sha256"] = fresh_hashes[path]
            if not isinstance(entry.get("confidence"), (int, float)):
                entry["confidence"] = 0.85

    except Exception as ex:
        logger.warning("Replan LLM call failed, updating hashes only", error=str(ex))
        # Fallback: keep original entries but update hashes
        updated_files = changed_file_entries
        for entry in updated_files:
            path = entry.get("path", "")
            if path in fresh_hashes:
                entry["sha256"] = fresh_hashes[path]

    # Merge: unchanged files keep their original entries, changed files get updated
    # Also refresh SHA256 for unchanged MODIFY files from the feature branch
    for entry in unchanged_files:
        path = entry.get("path", "")
        if entry.get("operation") == "MODIFY" and path:
            try:
                content = github.get_file_content(path, branch=target_branch)
                entry["sha256"] = sha256(content.encode("utf-8")).hexdigest()
            except Exception:
                # Keep original hash if we can't read from feature branch
                pass

    merged_files = unchanged_files + updated_files

    # Rebuild the implementation contract
    new_contract = {
        "files": merged_files,
        "protectedFiles": original_contract.get("protectedFiles", []),
        "allowedOperations": original_contract.get("allowedOperations", ["MODIFY", "CREATE"]),
        "validationChecklist": original_contract.get("validationChecklist", []),
    }

    # Build the planning output — reuse the original planning with updated contract
    original_planning = event.get("planning", {})
    planning = dict(original_planning)
    planning["implementationContract"] = new_contract
    planning["confidence"] = Decimal("0.85")

    # Update filesToGenerate for compatibility
    contract_files = [f["path"] for f in merged_files if f.get("path")]
    if contract_files:
        planning["filesToGenerate"] = contract_files

    return planning


def _replan_system_prompt() -> str:
    """System prompt for adaptive replanning."""
    return (
        "You are a senior software architect performing adaptive replanning.\n\n"
        "Context: A previous implementation plan was generated, but some target files\n"
        "have changed in the repository since then. You must update the plan for\n"
        "ONLY the changed files while preserving all other decisions.\n\n"
        "Rules:\n"
        "1. Only update entries for files that changed.\n"
        "2. Keep the same operation (MODIFY/CREATE) unless the file was deleted.\n"
        "3. Update expectedChanges to account for the new file content.\n"
        "4. Do NOT touch unchanged files.\n"
        "5. Return ONLY valid JSON.\n"
    )


def _replan_user_prompt(
    event: dict[str, Any],
    changed_file_entries: list[dict[str, Any]],
    fresh_contents: dict[str, str],
    original_contract: dict[str, Any],
) -> str:
    """Build user prompt for adaptive replanning of changed files."""
    import json

    # Build content section showing new file state
    files_section = ""
    for entry in changed_file_entries:
        path = entry.get("path", "")
        content = fresh_contents.get(path, "(could not download)")
        # Truncate to keep context manageable
        truncated = content[:3000] if len(content) > 3000 else content
        files_section += f"\n--- {path} (CURRENT CONTENT) ---\n{truncated}\n"

    return f"""Adaptive Replanning Required.

Ticket: {event.get("ticketId", "")}
Summary: {event.get("summary", "")}

The following files have changed since the original plan was created.
Update the implementation entries for ONLY these files.

--------------------------------------------------
CHANGED FILES (with their NEW content)
--------------------------------------------------
{files_section}
--------------------------------------------------
ORIGINAL IMPLEMENTATION ENTRIES (for these files)
--------------------------------------------------

{json.dumps(changed_file_entries, indent=2)}

--------------------------------------------------
ORIGINAL VALIDATION CHECKLIST
--------------------------------------------------

{json.dumps(original_contract.get("validationChecklist", []), indent=2)}

--------------------------------------------------
INSTRUCTIONS
--------------------------------------------------

1. For each changed file, update the "expectedChanges" to reflect
   what needs to happen given the NEW file content.
2. Keep the same "operation" (MODIFY) and "path".
3. Adjust "reason" if the change strategy needs updating.
4. Return a JSON object with exactly this format:

{{
  "files": [
    {{
      "path": "...",
      "operation": "MODIFY",
      "reason": "...",
      "expectedChanges": ["..."],
      "confidence": 0.85
    }}
  ]
}}

Return ONLY valid JSON. No markdown. No explanation."""


# ---------------------------------------------------------------------------
# Main handler
# ---------------------------------------------------------------------------


def lambda_handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Planning agent entry point."""
    logger.info("Planning agent started", workflow_id=event.get("workflowId"))

    config = PlanningConfig()
    workflow_id = event.get("workflowId")

    if not workflow_id:
        raise ValueError(f"workflowId missing from event: {event}")

    # Detect if this is an adaptive replan invocation
    is_replan = event.get("status") == "REPLAN_REQUIRED"
    replan_attempt = event.get("replanAttempt", 0)
    changed_files = event.get("changedFiles", [])
    original_contract = event.get("originalContract", {})

    if is_replan:
        logger.info(
            "Adaptive replanning started",
            workflow_id=workflow_id,
            replan_attempt=replan_attempt,
            changed_files=changed_files,
        )

    # Initialize services
    bedrock = BedrockClient(config.bedrock_model_id)
    s3 = S3Helper(config.s3_bucket)
    table = WorkflowTable(config.table_name)
    github = GitHubClient(
        owner=config.github_repo_owner,
        repo=config.github_repo_name,
        secret_name=config.github_secret_name,
    )

    # Load architecture knowledge base (generated by architecture agent)
    architecture_knowledge = _load_architecture_knowledge(s3)

    # -----------------------------------------------------------------------
    # Adaptive Replan Path
    # -----------------------------------------------------------------------
    if is_replan and changed_files and original_contract:
        planning = _adaptive_replan(
            bedrock=bedrock,
            github=github,
            event=event,
            changed_files=changed_files,
            original_contract=original_contract,
            architecture_knowledge=architecture_knowledge,
        )

        # Preserve replan metadata in the event
        planning["replanAttempt"] = replan_attempt
        planning["replanReason"] = "FILE_CHANGED"
        planning["replanChangedFiles"] = changed_files

        # Version the contract: Plan v1 is the original, Plan vN is this replan
        plan_version = replan_attempt + 1
        planning["planVersion"] = plan_version

        # Store this versioned plan separately (never overwrite v1)
        s3.upload_json(f"plans/{workflow_id}-v{plan_version}.json", planning)

        # Also store the original contract for reference (only on first replan)
        if replan_attempt == 1:
            s3.upload_json(f"plans/{workflow_id}-v1-original.json", event.get("planning", {}))

        # Update recovery history
        recovery_history = event.get("recoveryHistory", [])
        # The last entry was added by Development Agent with status REPLANNING
        # Update it to show planning completed
        if recovery_history and recovery_history[-1].get("status") == "REPLANNING":
            recovery_history[-1]["status"] = "REPLANNED"
            recovery_history[-1]["planVersion"] = plan_version

        planning["recoveryHistory"] = recovery_history

        # Persist status
        table.update_status(workflow_id=workflow_id, status="PLANNED", planning=planning)

        event["planning"] = planning
        event["status"] = "PLANNED"
        event["replanAttempt"] = replan_attempt
        event["recoveryHistory"] = recovery_history

        logger.info(
            "Adaptive replan complete",
            workflow_id=workflow_id,
            replan_attempt=replan_attempt,
            plan_version=plan_version,
            contract_files=len(planning.get("implementationContract", {}).get("files", [])),
        )

        return event

    # -----------------------------------------------------------------------
    # Phase 1: Generate Engineering Contract (normal path)
    # -----------------------------------------------------------------------
    try:
        planning = bedrock.converse_json(
            system_prompt=prompts.system_prompt(),
            user_prompt=prompts.user_prompt(
                workflow=event,
                architecture_knowledge=architecture_knowledge,
            ),
            max_tokens=4096,
        )

        # Validate and normalize Engineering Contract fields
        planning = _validate_engineering_contract(planning)

        # Enrich with confidence metrics
        planning["confidence"] = Decimal("0.95")
        planning["estimatedFiles"] = max(
            len(planning.get("filesToGenerate", [])),
            len(planning.get("affectedModules", [])) * 2,
            1,
        )

        logger.info(
            "Engineering Contract generated",
            workflow_id=workflow_id,
            change_type=planning.get("changeType"),
            risk_level=planning.get("riskLevel"),
            estimated_scope=planning.get("estimatedScope"),
            candidate_modules=planning.get("candidateModules"),
            files_to_generate=len(planning.get("filesToGenerate", [])),
            confidence=str(planning["confidence"]),
        )

    except Exception as ex:
        logger.error("Plan generation failed, using fallback", error=str(ex))
        planning = _build_fallback_plan(event, str(ex))

        # Persist fallback and return early
        table.update_status(workflow_id=workflow_id, status="PLANNED", planning=planning)
        s3.upload_json(f"plans/{workflow_id}.json", planning)
        event["planning"] = planning
        event["status"] = "PLANNED"
        return event

    # -----------------------------------------------------------------------
    # Phase 2: Search repository for relevant files
    # -----------------------------------------------------------------------
    keywords = _extract_keywords(event)
    logger.info("Keywords extracted for repo search", keywords=keywords)

    candidate_paths = _search_repository(
        github=github,
        keywords=keywords,
        candidate_modules=planning.get("candidateModules", []),
        expected_file_types=planning.get("expectedFileTypes", []),
        change_type=planning.get("changeType", ""),
    )

    # Download top candidate files
    file_contents, file_hashes = _download_candidates(github, candidate_paths)
    logger.info(
        "Candidate files downloaded",
        downloaded_count=len(file_contents),
    )

    # -----------------------------------------------------------------------
    # Phase 3: Generate Implementation Contract
    # -----------------------------------------------------------------------
    implementation_contract = _generate_implementation_contract(
        bedrock=bedrock,
        event=event,
        planning=planning,
        candidate_paths=candidate_paths,
        file_contents=file_contents,
        file_hashes=file_hashes,
        architecture_knowledge=architecture_knowledge,
    )

    # Attach implementation contract to the planning output
    planning["implementationContract"] = implementation_contract

    # Update filesToGenerate for backward compatibility only.
    # The Development Agent should consume implementationContract instead.
    contract_files = [f["path"] for f in implementation_contract.get("files", []) if f.get("path")]
    if contract_files:
        planning["filesToGenerate"] = contract_files

    # -----------------------------------------------------------------------
    # Persist and return
    # -----------------------------------------------------------------------
    # Mark as Plan v1 (initial)
    planning["planVersion"] = 1

    table.update_status(
        workflow_id=workflow_id,
        status="PLANNED",
        planning=planning,
    )

    # Store plan artifact in S3 as v1
    s3.upload_json(f"plans/{workflow_id}.json", planning)
    s3.upload_json(f"plans/{workflow_id}-v1.json", planning)

    # Enrich workflow event for next step
    event["planning"] = planning
    event["status"] = "PLANNED"

    logger.info(
        "Planning complete with implementation contract",
        workflow_id=workflow_id,
        contract_files=len(contract_files),
        protected_files=len(implementation_contract.get("protectedFiles", [])),
    )

    return event
