"""
Planning Agent Lambda Handler.

Reads the project architecture knowledge base (generated by the Architecture Agent)
and uses it to produce a ticket-specific implementation plan via Bedrock.

Input: Workflow event from Step Functions containing ticket information.
Output: Workflow event enriched with 'planning' and status 'PLANNED'.
"""

from decimal import Decimal
from typing import Any

from shared.bedrock_client import BedrockClient
from shared.config import PlanningConfig
from shared.dynamodb_helper import WorkflowTable
from shared.logger import get_logger
from shared.prompts import planning as prompts
from shared.s3_helper import S3Helper

logger = get_logger(__name__, agent="planning")


def _load_architecture_knowledge(s3: S3Helper) -> dict[str, Any] | None:
    """
    Load the architecture knowledge base from S3.

    This is the JSON generated by the Architecture Agent.
    Returns None if not available (first run, or architecture agent hasn't run yet).
    """
    try:
        if s3.object_exists("architecture/knowledge.json"):
            knowledge = s3.download_json("architecture/knowledge.json")
            logger.info("Architecture knowledge loaded from S3")
            return knowledge
    except Exception as ex:
        logger.warning("Could not load architecture knowledge", error=str(ex))

    return None


def lambda_handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Planning agent entry point."""
    logger.info("Planning agent started", workflow_id=event.get("workflowId"))

    config = PlanningConfig()
    workflow_id = event.get("workflowId")

    if not workflow_id:
        raise ValueError(f"workflowId missing from event: {event}")

    # Initialize services
    bedrock = BedrockClient(config.bedrock_model_id)
    s3 = S3Helper(config.s3_bucket)
    table = WorkflowTable(config.table_name)

    # Load architecture knowledge base (generated by architecture agent)
    architecture_knowledge = _load_architecture_knowledge(s3)

    # Generate implementation plan
    try:
        planning = bedrock.converse_json(
            system_prompt=prompts.system_prompt(),
            user_prompt=prompts.user_prompt(
                workflow=event,
                architecture_knowledge=architecture_knowledge,
            ),
            max_tokens=4096,
        )

        # Enrich with confidence metrics
        planning["confidence"] = Decimal("0.95")
        planning["estimatedFiles"] = max(
            len(planning.get("filesToGenerate", [])),
            len(planning.get("affectedModules", [])) * 2,
            1,
        )

        logger.info(
            "Plan generated successfully",
            workflow_id=workflow_id,
            files_to_generate=len(planning.get("filesToGenerate", [])),
            confidence=str(planning["confidence"]),
        )

    except Exception as ex:
        logger.error("Plan generation failed, using fallback", error=str(ex))

        planning = {
            "summary": event.get("summary", ""),
            "requirements": [],
            "acceptanceCriteria": [],
            "implementationPlan": [],
            "testCases": [],
            "affectedModules": [],
            "technologies": [],
            "filesToGenerate": [],
            "confidence": Decimal("0.50"),
            "estimatedFiles": 0,
            "error": str(ex),
        }

    # Persist to DynamoDB
    table.update_status(
        workflow_id=workflow_id,
        status="PLANNED",
        planning=planning,
    )

    # Store plan artifact in S3
    s3.upload_json(f"plans/{workflow_id}.json", planning)

    # Enrich workflow event for next step
    event["planning"] = planning
    event["status"] = "PLANNED"

    return event
