"""
Planning Agent Lambda Handler.

Reads the project architecture knowledge base (generated by the Architecture Agent)
and uses it to produce a ticket-specific Engineering Contract via Bedrock.

The Engineering Contract extends the traditional implementation plan with:
- Change classification (changeType, intent, riskLevel, estimatedScope)
- Module analysis (candidateModules, expectedFileTypes, avoidFileTypes)
- Safety constraints (expectedChanges, mustNotChange, validationChecklist)

Input: Workflow event from Step Functions containing ticket information.
Output: Workflow event enriched with 'planning' and status 'PLANNED'.
"""

from decimal import Decimal
from typing import Any

from shared.bedrock_client import BedrockClient
from shared.config import PlanningConfig
from shared.dynamodb_helper import WorkflowTable
from shared.logger import get_logger
from shared.prompts import planning as prompts
from shared.s3_helper import S3Helper

logger = get_logger(__name__, agent="planning")

# Valid values for enum-like fields (used for validation/defaults)
VALID_CHANGE_TYPES = {
    "BUG_FIX",
    "NEW_FEATURE",
    "ENHANCEMENT",
    "REFACTOR",
    "CONFIGURATION",
    "DOCUMENTATION",
}
VALID_RISK_LEVELS = {"LOW", "MEDIUM", "HIGH"}
VALID_SCOPES = {"SMALL", "MEDIUM", "LARGE"}


def _load_architecture_knowledge(s3: S3Helper) -> dict[str, Any] | None:
    """
    Load the architecture knowledge base from S3.

    This is the JSON generated by the Architecture Agent.
    Returns None if not available (first run, or architecture agent hasn't run yet).
    """
    try:
        if s3.object_exists("architecture/knowledge.json"):
            knowledge = s3.download_json("architecture/knowledge.json")
            logger.info("Architecture knowledge loaded from S3")
            return knowledge
    except Exception as ex:
        logger.warning("Could not load architecture knowledge", error=str(ex))

    return None


def _validate_engineering_contract(planning: dict[str, Any]) -> dict[str, Any]:
    """
    Validate and normalize Engineering Contract fields.

    Ensures all new fields exist with correct types and valid enum values.
    Falls back to sensible defaults if the LLM returned unexpected values.

    Args:
        planning: Raw planning dict from Bedrock.

    Returns:
        Planning dict with validated Engineering Contract fields.
    """
    # Validate changeType
    change_type = planning.get("changeType", "")
    if change_type not in VALID_CHANGE_TYPES:
        planning["changeType"] = "ENHANCEMENT"
        logger.warning(
            "Invalid changeType from LLM, defaulting to ENHANCEMENT",
            raw_value=change_type,
        )

    # Validate intent (must be a non-empty string)
    if not isinstance(planning.get("intent"), str) or not planning["intent"].strip():
        planning["intent"] = planning.get("summary", "")

    # Validate list fields — ensure they are lists
    list_fields = [
        "candidateModules",
        "expectedFileTypes",
        "avoidFileTypes",
        "expectedChanges",
        "mustNotChange",
        "validationChecklist",
    ]
    for field in list_fields:
        if not isinstance(planning.get(field), list):
            planning[field] = []

    # Validate riskLevel
    risk_level = planning.get("riskLevel", "")
    if risk_level not in VALID_RISK_LEVELS:
        planning["riskLevel"] = "MEDIUM"
        logger.warning(
            "Invalid riskLevel from LLM, defaulting to MEDIUM",
            raw_value=risk_level,
        )

    # Validate estimatedScope
    scope = planning.get("estimatedScope", "")
    if scope not in VALID_SCOPES:
        planning["estimatedScope"] = "MEDIUM"
        logger.warning(
            "Invalid estimatedScope from LLM, defaulting to MEDIUM",
            raw_value=scope,
        )

    return planning


def _build_fallback_plan(event: dict[str, Any], error: str) -> dict[str, Any]:
    """
    Build a fallback planning dict when Bedrock call fails.

    Includes both legacy fields and new Engineering Contract fields
    to maintain backward compatibility.

    Args:
        event: The workflow event with ticket information.
        error: Error message from the failed Bedrock call.

    Returns:
        Fallback planning dict.
    """
    return {
        # Legacy fields
        "summary": event.get("summary", ""),
        "requirements": [],
        "acceptanceCriteria": [],
        "implementationPlan": [],
        "testCases": [],
        "affectedModules": [],
        "technologies": [],
        "filesToGenerate": [],
        # Engineering Contract fields
        "changeType": "ENHANCEMENT",
        "intent": event.get("summary", ""),
        "candidateModules": [],
        "expectedFileTypes": [],
        "avoidFileTypes": [],
        "expectedChanges": [],
        "mustNotChange": [],
        "validationChecklist": [],
        "riskLevel": "MEDIUM",
        "estimatedScope": "MEDIUM",
        # Metadata
        "confidence": Decimal("0.50"),
        "estimatedFiles": 0,
        "error": error,
    }


def lambda_handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Planning agent entry point."""
    logger.info("Planning agent started", workflow_id=event.get("workflowId"))

    config = PlanningConfig()
    workflow_id = event.get("workflowId")

    if not workflow_id:
        raise ValueError(f"workflowId missing from event: {event}")

    # Initialize services
    bedrock = BedrockClient(config.bedrock_model_id)
    s3 = S3Helper(config.s3_bucket)
    table = WorkflowTable(config.table_name)

    # Load architecture knowledge base (generated by architecture agent)
    architecture_knowledge = _load_architecture_knowledge(s3)

    # Generate Engineering Contract
    try:
        planning = bedrock.converse_json(
            system_prompt=prompts.system_prompt(),
            user_prompt=prompts.user_prompt(
                workflow=event,
                architecture_knowledge=architecture_knowledge,
            ),
            max_tokens=4096,
        )

        # Validate and normalize Engineering Contract fields
        planning = _validate_engineering_contract(planning)

        # Enrich with confidence metrics
        planning["confidence"] = Decimal("0.95")
        planning["estimatedFiles"] = max(
            len(planning.get("filesToGenerate", [])),
            len(planning.get("affectedModules", [])) * 2,
            1,
        )

        logger.info(
            "Engineering Contract generated",
            workflow_id=workflow_id,
            change_type=planning.get("changeType"),
            risk_level=planning.get("riskLevel"),
            estimated_scope=planning.get("estimatedScope"),
            candidate_modules=planning.get("candidateModules"),
            files_to_generate=len(planning.get("filesToGenerate", [])),
            confidence=str(planning["confidence"]),
        )

    except Exception as ex:
        logger.error("Plan generation failed, using fallback", error=str(ex))
        planning = _build_fallback_plan(event, str(ex))

    # Persist to DynamoDB
    table.update_status(
        workflow_id=workflow_id,
        status="PLANNED",
        planning=planning,
    )

    # Store plan artifact in S3
    s3.upload_json(f"plans/{workflow_id}.json", planning)

    # Enrich workflow event for next step
    event["planning"] = planning
    event["status"] = "PLANNED"

    return event
