"""
Prompt builder for agent-specific LLM prompts.

Centralizes prompt construction so agents stay thin and prompts
are easy to iterate on in one place.

Usage:
    from shared.prompt_builder import PromptBuilder

    prompt = PromptBuilder.architecture_prompt(summary, tree, context)
    prompt = PromptBuilder.planning_prompt(workflow, architecture_knowledge)
    prompt = PromptBuilder.code_generation_prompt(workflow, file_path)
"""

import json
from typing import Any


class PromptBuilder:
    """Factory for constructing agent prompts."""

    # -------------------------------------------------------------------
    # Architecture Agent
    # -------------------------------------------------------------------

    @staticmethod
    def architecture_system() -> str:
        """System prompt for the architecture agent."""
        return (
            "You are a Senior Software Architect. "
            "You analyze repositories and produce structured architectural knowledge. "
            "Return only valid JSON. No markdown. No explanations."
        )

    @staticmethod
    def architecture_prompt(
        repository_summary: dict[str, Any],
        repository_tree: list[dict[str, Any]],
        project_context: dict[str, Any],
    ) -> str:
        """Build the user prompt for architecture knowledge generation."""
        return f"""Analyze this GitHub repository and generate long-term architectural knowledge.

This knowledge will be consumed by Planning, Development, Validation and Release agents.

DO NOT write code.
DO NOT generate implementation plans.
Only analyze the project structure and architecture.

--------------------------------------------------
Repository Summary
--------------------------------------------------

{json.dumps(repository_summary, indent=2)}

--------------------------------------------------
Repository Structure
--------------------------------------------------

{json.dumps(repository_tree, indent=2)}

--------------------------------------------------
Important Files
--------------------------------------------------

{json.dumps(project_context, indent=2)}

--------------------------------------------------

Generate EXACTLY this JSON structure:

{{
    "project": {{
        "name": "",
        "description": "",
        "businessPurpose": "",
        "technologyStack": [],
        "frameworks": [],
        "languages": [],
        "buildTools": [],
        "packageManagers": []
    }},
    "architecture": {{
        "style": "",
        "layers": [],
        "majorModules": [],
        "designPatterns": [],
        "externalDependencies": [],
        "configurationFiles": [],
        "entryPoints": []
    }},
    "repository": {{
        "importantDirectories": [],
        "importantFiles": [],
        "codingConventions": [],
        "namingConventions": [],
        "folderOrganization": ""
    }},
    "standards": {{
        "codingStandards": [],
        "testingStandards": [],
        "securityStandards": [],
        "documentationStandards": [],
        "deploymentStandards": []
    }},
    "metadata": {{
        "repositoryType": "",
        "primaryLanguage": "",
        "framework": "",
        "generatedBy": "Architecture Agent",
        "version": "1.0"
    }}
}}

Return ONLY valid JSON. No markdown. No explanations. No additional text."""

    # -------------------------------------------------------------------
    # Planning Agent
    # -------------------------------------------------------------------

    @staticmethod
    def planning_system() -> str:
        """System prompt for the planning agent."""
        return (
            "You are a senior software architect. "
            "You create detailed implementation plans based on project architecture "
            "and ticket requirements. "
            "Return only valid JSON. Do not use markdown or code fences."
        )

    @staticmethod
    def planning_prompt(
        workflow: dict[str, Any],
        architecture_knowledge: dict[str, Any] | None = None,
    ) -> str:
        """
        Build the user prompt for the planning agent.

        Args:
            workflow: The workflow event with ticket information.
            architecture_knowledge: Optional architecture knowledge from S3
                                    (generated by architecture agent).
        """
        architecture_section = ""
        if architecture_knowledge:
            architecture_section = f"""
--------------------------------------------------
Project Architecture (Knowledge Base)
--------------------------------------------------

{json.dumps(architecture_knowledge, indent=2)}

Use this architecture knowledge to inform your implementation plan.
Respect existing patterns, conventions, and folder organization.
"""

        return f"""Generate a detailed implementation plan for this ticket.

Return ONLY a valid JSON object.
Use EXACTLY the schema below.
Do not add extra fields. Do not rename fields.
Do not wrap the response in markdown.
Populate EVERY field with meaningful content.

For filesToGenerate, include all source files that should be created or modified
with realistic filenames that respect the project's folder organization.

--------------------------------------------------
Ticket Information
--------------------------------------------------

Ticket ID: {workflow.get("ticketId", "")}
Summary: {workflow.get("summary", "")}
Description: {workflow.get("description", "")}
Priority: {workflow.get("priority", "")}
Issue Type: {workflow.get("issueType", "")}
Project: {workflow.get("project", "")}
{architecture_section}
--------------------------------------------------
Required JSON Schema
--------------------------------------------------

{{
  "summary": "",
  "requirements": [],
  "acceptanceCriteria": [],
  "implementationPlan": [],
  "testCases": [],
  "affectedModules": [],
  "technologies": [],
  "filesToGenerate": []
}}"""

    # -------------------------------------------------------------------
    # Development Agent
    # -------------------------------------------------------------------

    @staticmethod
    def code_generation_system() -> str:
        """System prompt for code generation."""
        return (
            "You are an expert software engineer. "
            "Generate complete, production-ready code. "
            "Return ONLY the file contents. "
            "Do not wrap in markdown. Do not use code fences. "
            "Do not explain the code."
        )

    @staticmethod
    def code_generation_prompt(
        workflow: dict[str, Any],
        file_path: str,
    ) -> str:
        """
        Build the user prompt for code file generation.

        Args:
            workflow: Full workflow state including planning output.
            file_path: The file to generate.
        """
        planning = workflow.get("planning", {})

        return f"""Generate COMPLETE production-ready code for this file.

File to generate: {file_path}

--------------------------------------------------
Project Context
--------------------------------------------------

Summary: {planning.get("summary", "")}

Requirements:
{json.dumps(planning.get("requirements", []), indent=2)}

Acceptance Criteria:
{json.dumps(planning.get("acceptanceCriteria", []), indent=2)}

Implementation Plan:
{json.dumps(planning.get("implementationPlan", []), indent=2)}

Technologies:
{json.dumps(planning.get("technologies", []), indent=2)}

Affected Modules:
{json.dumps(planning.get("affectedModules", []), indent=2)}

--------------------------------------------------

Return ONLY the file contents for: {file_path}
Do not wrap in markdown. Do not use ``` fences. Do not explain."""

    # -------------------------------------------------------------------
    # Document builders (for architecture knowledge-base output)
    # -------------------------------------------------------------------

    @staticmethod
    def build_architecture_documents(architecture: dict[str, Any]) -> dict[str, Any]:
        """
        Convert raw architecture JSON into markdown documents + metadata.

        Returns:
            Dict of filename -> content (str or dict for JSON files).
        """
        project = architecture.get("project", {})
        arch = architecture.get("architecture", {})
        repository = architecture.get("repository", {})
        standards = architecture.get("standards", {})
        metadata = architecture.get("metadata", {})

        def _bullet(values: list) -> str:
            if not values:
                return "- None"
            return "\n".join(f"- {item}" for item in values)

        documents = {
            "project.md": f"""# Project

## Name
{project.get("name", "")}

## Description
{project.get("description", "")}

## Business Purpose
{project.get("businessPurpose", "")}

## Technology Stack
{_bullet(project.get("technologyStack", []))}

## Frameworks
{_bullet(project.get("frameworks", []))}

## Languages
{_bullet(project.get("languages", []))}

## Build Tools
{_bullet(project.get("buildTools", []))}

## Package Managers
{_bullet(project.get("packageManagers", []))}
""",
            "architecture.md": f"""# Architecture

## Style
{arch.get("style", "")}

## Layers
{_bullet(arch.get("layers", []))}

## Major Modules
{_bullet(arch.get("majorModules", []))}

## Design Patterns
{_bullet(arch.get("designPatterns", []))}

## External Dependencies
{_bullet(arch.get("externalDependencies", []))}

## Configuration Files
{_bullet(arch.get("configurationFiles", []))}

## Entry Points
{_bullet(arch.get("entryPoints", []))}
""",
            "repository.md": f"""# Repository

## Important Directories
{_bullet(repository.get("importantDirectories", []))}

## Important Files
{_bullet(repository.get("importantFiles", []))}

## Coding Conventions
{_bullet(repository.get("codingConventions", []))}

## Naming Conventions
{_bullet(repository.get("namingConventions", []))}

## Folder Organization
{repository.get("folderOrganization", "")}
""",
            "standards.md": f"""# Standards

## Coding Standards
{_bullet(standards.get("codingStandards", []))}

## Testing Standards
{_bullet(standards.get("testingStandards", []))}

## Security Standards
{_bullet(standards.get("securityStandards", []))}

## Documentation Standards
{_bullet(standards.get("documentationStandards", []))}

## Deployment Standards
{_bullet(standards.get("deploymentStandards", []))}
""",
            "metadata.json": metadata,
        }

        return documents
